### ISSUE TITLE
> Could not get unknown property 'isPresent' 

### ISSUE THREAD

**Issue by nschild** [uzzu/dotenv-gradle#51]
Hi,
I am getting this error: > Could not get unknown property 'isPresent' for extension 'KEYSTORE_FILE' of type co.uzzu.dotenv.gradle.DotEnvProperty.

.env

    KEYSTORE_FILE = file.keystore
    KEYSTORE_PASS = xxx
    KEYSTORE_ALIAS = xxx
    KEYSTORE_ALIAS_PASS = xxx

.env.template

    KEYSTORE_FILE =
    KEYSTORE_PASS =
    KEYSTORE_ALIAS =
    KEYSTORE_ALIAS_PASS = 

build.gradle

    ...
    buildTypes {
        release {
            if (env.KEYSTORE_FILE.isPresent){
                signingConfig signingConfigs.release
            }
        }
    }
    ...

Gradle 6.7.1
co.uzzu.dotenv.gradle.gradle.plugin:2.0.0

**Comment by uzzu** [comment]
You could not insert space outside `=` . This is by design.

refs:
- https://unix.stackexchange.com/questions/258727/spaces-in-variable-assignments-in-shell-scripts
- https://www.digitalocean.com/community/tutorials/how-to-read-and-set-environmental-and-shell-variables-on-linux

Please reopen this issue if you could not solve your problem.
